[build]
  command = "npm run build"  # ya da "yarn build", build komutunu çalıştıracak
  publish = "dist"  # Build çıktı dizini
  
[build.environment]
  NODE_VERSION = "18"  # Node.js versiyonunu belirtin
